import type { DashboardData } from './types';

const now = new Date();
const iso = (minutesAgo: number) => new Date(now.getTime() - minutesAgo * 60_000).toISOString();

export const fallbackDashboard: DashboardData = {
  collectorRunning: true,
  activeContext: null,
  categoryOptions: [
    { name: '开发', color: '#60a5fa', isBuiltin: true },
    { name: '学习', color: '#a78bfa', isBuiltin: true },
    { name: '写作', color: '#f472b6', isBuiltin: true },
    { name: '沟通', color: '#34d399', isBuiltin: true },
    { name: '娱乐', color: '#fb7185', isBuiltin: true },
    { name: '杂务', color: '#fbbf24', isBuiltin: true },
    { name: '无效', color: '#94a3b8', isBuiltin: true },
  ],
  settings: {
    language: 'zh-CN',
    theme: 'light',
    pollIntervalSeconds: 1,
    heartbeatSeconds: 5,
    rawEventRetentionDays: 30,
    idleThresholdSeconds: 180,
    idleCategory: '无效',
    idleProjectName: '离开',
    passiveContentCountsAsActive: true,
    autoMaintenance: true,
    autoStart: true,
    launchAtLogin: false,
    quickPauseEnabled: true,
    aiMode: 'off',
    aiProvider: 'codex-account',
    aiReviewScope: 'fallback',
    minAiSessionMinutes: 1,
    aiReviewDelaySessions: 10,
    codexPlan: 'pro-20x',
    aiBaseUrl: 'https://api.openai.com/v1',
    aiModel: 'gpt-5.6-luna',
    aiSecretRef: null,
    backupDir: null,
    captureScope: 'metadata-only',
    fps: 0,
    chunkMinutes: 0,
    analysisTiming: 'local-only',
    tempStorageLimitGb: 1,
  },
  projects: [
    { id: 'p1', name: 'ScreenUse', category: '开发', source: 'workspace-auto', color: '#60a5fa', description: '根据 VS Code 工作区自动识别', createdAt: iso(700), updatedAt: iso(5) },
    { id: 'p2', name: '课程与论文', category: '学习', source: 'manual', color: '#a78bfa', description: '课程、论文和资料阅读', createdAt: iso(1200), updatedAt: iso(45) },
    { id: 'p3', name: '日常事务', category: '杂务', source: 'manual', color: '#fbbf24', description: '零散电脑事务', createdAt: iso(1800), updatedAt: iso(90) },
  ],
  tasks: [
    { id: 't1', projectId: 'p1', title: '日常开发', status: 'active', source: 'workspace-auto', plannedDueAt: null, createdAt: iso(700), updatedAt: iso(5) },
    { id: 't4', projectId: 'p1', title: '界面优化', status: 'active', source: 'manual', plannedDueAt: null, createdAt: iso(500), updatedAt: iso(3) },
    { id: 't2', projectId: 'p2', title: '资料阅读', status: 'active', source: 'manual', plannedDueAt: null, createdAt: iso(1200), updatedAt: iso(45) },
    { id: 't3', projectId: 'p3', title: '日常事务', status: 'active', source: 'manual', plannedDueAt: null, createdAt: iso(1800), updatedAt: iso(90) },
  ],
  sessions: [
    { id: 's1', startedAt: iso(188), endedAt: iso(126), projectId: 'p1', projectName: 'ScreenUse', taskId: 't1', taskTitle: '日常开发', category: '开发', summary: 'ScreenUse · collectors.rs', confidence: 0.91, userConfirmed: false, source: 'collector-rule', evidence: [{ kind: 'workspace', label: '工作区', value: 'ScreenUse', weight: 0.8 }, { kind: 'app', label: '应用', value: 'Code.exe', weight: 0.5 }] },
    { id: 's1b', startedAt: iso(126), endedAt: iso(120), projectId: 'p1', projectName: 'ScreenUse', taskId: 't1', taskTitle: '日常开发', category: '开发', summary: 'ScreenUse · cargo test', confidence: 0.88, userConfirmed: false, source: 'collector-rule', evidence: [{ kind: 'window', label: '窗口', value: 'cargo test', weight: 0.7 }, { kind: 'app', label: '应用', value: 'WindowsTerminal.exe', weight: 0.5 }] },
    { id: 's2', startedAt: iso(118), endedAt: iso(76), projectId: 'p2', projectName: '课程与论文', taskId: 't2', taskTitle: '资料阅读', category: '学习', summary: 'arxiv.org · 时间追踪研究', confidence: 0.79, userConfirmed: false, source: 'collector-rule', evidence: [{ kind: 'url', label: '网页', value: 'https://arxiv.org', weight: 0.7 }, { kind: 'app', label: '应用', value: 'msedge.exe', weight: 0.5 }] },
    { id: 's3', startedAt: iso(68), endedAt: iso(39), projectId: 'p1', projectName: 'ScreenUse', taskId: 't4', taskTitle: '界面优化', category: '开发', summary: 'ScreenUse · App.tsx', confidence: 0.89, userConfirmed: true, source: 'collector-rule', evidence: [{ kind: 'file', label: '文件', value: 'src/App.tsx', weight: 0.8 }, { kind: 'app', label: '应用', value: 'Code.exe', weight: 0.5 }] },
    { id: 's4', startedAt: iso(32), endedAt: iso(8), projectId: null, projectName: null, taskId: null, taskTitle: null, category: '杂务', summary: 'Chrome · 新标签页', confidence: 0.56, userConfirmed: false, source: 'context-complete', evidence: [{ kind: 'window', label: '窗口', value: '新标签页', weight: 0.5 }, { kind: 'app', label: '应用', value: 'chrome.exe', weight: 0.5 }] },
  ],
  planItems: [],
  trends: [
    { label: 'ScreenUse', value: 91, group: '开发' },
    { label: '课程与论文', value: 42, group: '学习' },
    { label: '未归类', value: 24, group: '杂务' },
  ],
  categories: [
    { label: '开发', value: 91, group: '开发' },
    { label: '学习', value: 42, group: '学习' },
    { label: '杂务', value: 24, group: '杂务' },
  ],
  queue: {
    pending: 0,
    running: 0,
    failed: 0,
    downgraded: 0,
    tempStorageGb: 0,
    tempStorageLimitGb: 1,
    personalMemoryCount: 0,
    personalMemoryUses: 0,
  },
};
